server:
  port: 8081
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.50.129:61616
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic
